import type { Metadata } from "next";
import { Nunito } from 'next/font/google'
import "./globals.css";
import Header from "@/components/common/Header";
import Footer from "@/components/common/Footer";

const nunito = Nunito({
  variable: '--font-nunito',
  subsets: ['latin'],
  display: 'swap',
  // weight: ['400', '700'], // Optional: specify weights
});

export const metadata: Metadata = {
  title: "Tobams Group",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased ${nunito.variable} ${nunito.className} scroll-smooth`}
    >
      <head>
        <link rel="icon" href="/favicon.png" />
      </head>
      <body className={`min-h-full flex flex-col w-full bg-white`}>
        <Header />
        <div className="grow overflow-x-hidden">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
